# Set up connections to other services:
server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://planner-mariadb:3306/planner}
    username: ${SPRING_DATASOURCE_USERNAME:planner}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mariadb.jdbc.Driver}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

    # database-platform: org.hibernate.dialect.MariaDBDialect

  web:
    mvc:
      log-request-details: true

logging:
  level:
    org:
      springframework: INFO
      springframework.security: ${LOGGING_LEVEL_SPRING_SECURITY:INFO}
      springframework.web: ${LOGGING_LEVEL_SPRING_WEB:INFO}
      springframework.cloud.gateway: ${LOGGING_LEVEL_SPRING_CLOUD:INFO}
    com:
      zaxxer.hikari: DEBUG