
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    workflow_dispatch:

permissions:
  contents: write

jobs:
  build-back:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          echo "Building the backend..."
          cd planner-backend
          chmod +x mvnw
          ./mvnw clean package

      - name: Build container
        run: |
          echo "Building the container..."
          sudo docker compose -f shichtconfig/docker/docker-compose-test.yml build
        with:
          sudo-pass: ${{ secrets.SUDO_PASS }}

      - name: Run container
        run: |
          echo "Running the container..."
          sudo docker compose -f shichtconfig/docker/docker-compose-test.yml down || true
          sudo docker compose -f shichtconfig/docker/docker-compose-test.yml up -d
        with:
          sudo-pass: ${{ secrets.SUDO_PASS }}
           
#  build-front: