
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    workflow_dispatch:

permissions:
  contents: write

jobs:
  build-back:
    runs-on: self-hosted
    steps:
      - name: Verify Docker
        run: |
          docker --version
          docker compose --version
          sudo systemctl status docker || sudo systemctl start docker

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          echo "Building the backend..."
          cd planner-backend
          ./mvnw clean package

      - name: Build container
        run: |
          echo "Building the container..."
          docker compose -f shichtconfig/docker/docker-compose-test.yml build

      - name: Run container
        run: |
          echo "Running the container..."
          docker compose -f shichtconfig/docker/docker-compose-test.yml down || true
          docker compose -f shichtconfig/docker/docker-compose-test.yml up -d 
           
#  build-front: