name: Stop Alles Containers

on:
  workflow_dispatch:

jobs:
  stop-backend:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop container
        run: |
          echo "Stopping the container..."
          docker compose -f schichtconfig/docker/docker-compose.yml down || true